apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquito-mqtt.fullname" . }}
  labels:
    {{- include "mosquito-mqtt.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}

  selector:
    {{- include "mosquito-mqtt.selectorLabels" . | nindent 4 }}

  ports:
  {{- range $name, $p := .Values.ports }}
    - name: {{ $name }}
      port: {{ $p.port }}
      targetPort: {{ $name }}
      protocol: {{ default "TCP" $p.protocol }}
      {{- if $p.nodePort }}
      nodePort: {{ $p.nodePort }}
      {{- end }}
  {{- end }}
