{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-duplicati-config
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  storageClassName: {{ .Values.persistence.config.storageClassName }}
---
{{- end }}

{{- if .Values.persistence.source.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-duplicati-source
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.source.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.source.size }}
  storageClassName: {{ .Values.persistence.source.storageClassName }}
---
{{- end }}

{{- if .Values.persistence.backups.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-duplicati-backups
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.backups.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
  storageClassName: {{ .Values.persistence.backups.storageClassName }}
---
{{- end }}

{{- if .Values.persistence.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-duplicati-nfs
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.persistence.nfs.size }}
  accessModes:
    - {{ .Values.persistence.nfs.accessMode }}
  nfs:
    server: {{ .Values.persistence.nfs.server }}
    path: {{ .Values.persistence.nfs.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-duplicati-nfs
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.nfs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.nfs.size }}
  storageClassName: {{ .Values.persistence.nfs.storageClassName }}
  volumeName: pv-duplicati-nfs
{{- end }}
